#!/usr/bin/env node

// This is a dummy entrypoint, specifically written so that it
// adds "--harmony" when running the node script, because I
// wanted to use weird ES6 stuff, but didnt want to transpile
// TODO: no longer need --harmony flag, get rid of this?

// Create a process spawner
const spawn = require('child_process').spawn;

// Compile a list of args
// Find the current path, append the real entrypoint name
// Drop the first 2 args (these are current file path and... something else, I forget)
const args = [`${__dirname}/nwsh.js`].concat(process.argv.slice(2));

// Spawn a new process, call node, add the arguments from above
// And redirect output to the console.
spawn(process.argv[0], args, { stdio: [0, 1, 2] });
